// Generated by Wrangler on Sun Jun 16 2024 00:13:24 GMT+0900 (Korean Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
}
