// Generated by Wrangler on Sat Jun 15 2024 22:58:46 GMT+0900 (Korean Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
}
